[versions]
# Required stuff, https://fabricmc.net/develop/
minecraft = "1.21.10"
yarnMappings = "1.21.10+build.2"
fabricLoader = "0.17.3"

loom = "1.12-SNAPSHOT" # https://github.com/FabricMC/fabric-loom/releases

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarnMappings" }
fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }

[bundles]

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }